### ISSUE TITLE
Abandoned files fix needed.

### ISSUE THREAD

**Issue by Justinzobel** [evolve-os/ypkg#1]
There are abandoned files under the install dir (/var/eopkg/keyutils-1.5.9-1/install):
    - /etc/request-key.d

It's a folder it seems and it's empty...

**Comment by ikeydoherty** [comment]
What is keyutils and why does it see fit to install an empty directory.. ?

**Comment by Justinzobel** [comment]
Linux Key Management Utilities a dependency of cifs-utils.

**Comment by ikeydoherty** [comment]
Gotcha. Can see the problem ^^
